# .github/workflows/setup-docs.yml
name: Setup Documentation

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'templates/**'
      - '.github/workflows/setup-docs.yaml'

jobs:
  # tocs-update:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     pull-requests: write
  #   steps:
  #   - uses: actions/checkout@v6
  #     with:
  #       ref: ${{ github.event.pull_request.head.ref }}
  #       token: ${{ secrets.GITHUB_TOKEN }}

  #   - name: Set up Node.js (for doctoc)
  #     uses: actions/setup-node@v6
  #     with:
  #       node-version: '22'

  #   - name: Install DocToc
  #     run: npm install -g doctoc

  #   - name: Generate / Update TOC in markdown files
  #     run: |
  #       # generate or update TOC in all markdown files
  #       # --notitle removes the default "Table of Contents" header
  #       find . -name '*.md' -not -path './node_modules/*' -not -path './.git/*' -exec doctoc {} --notitle \;

  #   - name: Commit updated TOC(s) if changed
  #     uses: stefanzweifel/git-auto-commit-action@v7
  #     with:
  #       commit_message: "[skip ci] docs: updated TOCs in all files"
  #       branch: ${{ github.event.pull_request.head.ref }}

  lint-markdown:
    # needs: [ tocs-update ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:

    - name: Check out repository code
      uses: actions/checkout@v6
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: DavidAnson/markdownlint-cli2-action@v22
      with:
        globs: |
          **/*.md
          !CHANGELOG.md
        # !templates/**
        fix: true

    - name: Set up Git identity
      run: |
        git config --global user.email "innovation_r&d@longwave.it"
        git config --global user.name "ActionBot"

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "[skip ci] docs: markdown lint fixes applied"
        branch: ${{ github.event.pull_request.head.ref }}
